---
general:
  buildTool: "mta"
service:
  buildToolVersion: "MBTJ17N18" #see SAP Continuous Integration and Delivery service for more build tool version options
stages:
  Build:
    mavenExecuteStaticCodeChecks: false
    npmExecuteLint: true
  Additional Unit Tests:
    npmExecuteScripts: false
  Acceptance:
    cloudFoundryDeploy: false
    cfApiEndpoint: "https://api.cf.us10-001.hana.ondemand.com"
    cfOrg: "c96f2572_dpedev"
    cfSpace: "dev"
    cfAppName: "app1"
    cfCredentialsId: "cf"
    uiVeri5ExecuteTests: false

  Release:
    cloudFoundryDeploy: true
    cfApiEndpoint: "https://api.cf.us10-001.hana.ondemand.com"
    cfOrg: "c96f2572_dpedev"
    cfSpace: "dev"
    cfAppName: "app1"
    cfCredentialsId: "cf"
    deployType: "standard"
    uiVeri5ExecuteTests: false
steps:
  artifactPrepareVersion:
    versioningType: "cloud_noTag"
  npmExecuteLint:
    failOnError: true
  cloudFoundryDeploy:
    mtaDeployParameters: "-f --version-rule ALL"
  tmsUpload:
    nodeName: "tmsqa"
    credentialsId: "ctms"